#version 450
#extension GL_EXT_nonuniform_qualifier : require
// #extension GL_EXT_debug_printf : enable

// specialization constants
layout(local_size_x_id = 0,
       local_size_y_id = 1,
       local_size_z_id = 2) in;

layout(push_constant) uniform PushConst
{
    uint N;
    uint aDescriptorIndex;
    uint bDescriptorIndex;
    uint outDescriptorIndex;
} pushConstants;

layout (set = 0, binding = 0) buffer DataDescriptors {
    float data[];
} dataDescriptors[];

void main() {
    const uint globalIdX = gl_GlobalInvocationID.x;

    if(globalIdX >= pushConstants.N){
        return;
    }

    const uint aInd = nonuniformEXT(pushConstants.aDescriptorIndex);
    const uint bInd = nonuniformEXT(pushConstants.bDescriptorIndex);
    const uint outInd = nonuniformEXT(pushConstants.outDescriptorIndex);

    const float a = dataDescriptors[aInd].data[globalIdX];
    const float b = dataDescriptors[bInd].data[globalIdX];
    const float result = a + b;

    dataDescriptors[outInd].data[globalIdX] = result;

    // debugPrintfEXT("%d\n", gl_LocalInvocationID.x);
}
