#version 450
#extension GL_EXT_nonuniform_qualifier : require
// #extension GL_EXT_debug_printf : enable

// specialization constants
layout(local_size_x_id = 0,
       local_size_y_id = 1,
       local_size_z_id = 2) in;

layout(push_constant) uniform PushConst
{
    uint N;
    uint aDescriptorIndex;
    uint bDescriptorIndex;
    uint outDescriptorIndex;
} pushConstants;

layout (set = 0, binding = 0) buffer DataDescriptors {
    vec4 data[];
} dataDescriptors[];

void main() {
    uvec2 gid = gl_GlobalInvocationID.xy;
    uint gridWidth = gl_NumWorkGroups.x * gl_WorkGroupSize.x;
    uint index = gid.y * gridWidth + gid.x;

    uint vecCount = pushConstants.N / 4;

    if (index >= vecCount) {
        return;
    }

    uint aInd  = nonuniformEXT(pushConstants.aDescriptorIndex);
    uint bInd  = nonuniformEXT(pushConstants.bDescriptorIndex);
    uint outInd = nonuniformEXT(pushConstants.outDescriptorIndex);

    vec4 a = dataDescriptors[aInd].data[index];
    vec4 b = dataDescriptors[bInd].data[index];
    dataDescriptors[outInd].data[index] = a + b;
}