#version 450
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_arithmetic : require

layout(local_size_x_id = 0,
       local_size_y_id = 1,
       local_size_z_id = 2) in;

layout(push_constant) uniform PushConst
{
    uint N;
    uint inDescriptorIndex;
    uint outDescriptorIndex;
} pushConstants;

layout (set = 0, binding = 0) buffer DataDescriptorsIn {
    float data[];
} dataDescriptorsIn[];

layout (set = 0, binding = 0) writeonly buffer DataDescriptorsOut {
    uint data[];
} dataDescriptorsOut[];

shared uint sMinOrdered;
shared uint sMaxOrdered;

uint toOrdered(float v)
{
    // takes float's bit representation and applies it to uint
    uint u = floatBitsToUint(v);
    // need to "order" float range [-inf, +inf] to [0, uint_max] range
    // negative float has 1 in sign mit (the most significant bit), making uint representation huge
    return (u & 0x80000000u) != 0u ? ~u : (u ^ 0x80000000u);
}

void main()
{
    const uint globalIdX = gl_GlobalInvocationID.x;
    const uint localIdx = gl_LocalInvocationID.x;

    if (localIdx == 0)
    {
        sMinOrdered = 0xFF800000u; // ordered +INF
        sMaxOrdered = 0x007FFFFFu; // ordered -INF
    }

    barrier();

    float invocationMin;
    float invocationMax;

    if(globalIdX < pushConstants.N){
        const uint inInd = nonuniformEXT(pushConstants.inDescriptorIndex);

        const float f = dataDescriptorsIn[inInd].data[globalIdX];
        
        invocationMin = f;
        invocationMax = f;
    }
    else
    {
        invocationMin = 1.0 / 0.0;
        invocationMax = -1.0 / 0.0;
    }

    float subgroupMin = subgroupMin(invocationMin);
    float subgroupMax = subgroupMax(invocationMax);

    if (subgroupElect())
    {
        uint subgroupMinOrdered = toOrdered(subgroupMin);
        uint subgroupMaxOrdered = toOrdered(subgroupMax);

        atomicMin(sMinOrdered, subgroupMinOrdered);
        atomicMin(sMaxOrdered, subgroupMaxOrdered);
    }

    barrier();

    if (localIdx == 0)
    {
        const uint outInd = nonuniformEXT(pushConstants.outDescriptorIndex);

        atomicMin(dataDescriptorsOut[outInd].data[0], sMinOrdered);
        atomicMax(dataDescriptorsOut[outInd].data[1], sMaxOrdered);
    }
}