#version 450
#extension GL_EXT_nonuniform_qualifier : require

layout(local_size_x_id = 0,
       local_size_y_id = 1,
       local_size_z_id = 2) in;

layout(push_constant) uniform PushConst
{
    uint inDescriptorIndex;
} pushConstants;

layout (set = 0, binding = 0) buffer DataDescriptorsIn {
    uint data[];
} dataDescriptorsIn[];

void main()
{
    const uint globalIdX = gl_GlobalInvocationID.x;

    if(globalIdX >= 2){
        return;
    }

    const uint inInd = nonuniformEXT(pushConstants.inDescriptorIndex);

    dataDescriptorsIn[inInd].data[0] = 0xFF800000u; // +inf ordered
    dataDescriptorsIn[inInd].data[1] = 0x007FFFFF; // -inf ordered
}